Switch all descriptions from .NET Core to .NET
NotMyself/DotNetCoreKoans pull request #184
Opened 2023-04-06 20:14 UTC by KGonzalezASC

The commits are staged in 3 pushes so it is possible to cherry-pick was it an acceptable changed.

Here are all changes:

-About Delegates.cs: .Net → .NET

-About Exceptions.cs: executing and something were misspelled.

-About Float.cs: Changes all references from .NET Core to just .NET

-About Generic Containers.cs: .Net →.NET

-.tours were updated

-Attempted to updated README.md picture name and updated contents that I thought was safe to change. Any links existing with reference to old (dotnetcorekoans) naming scheme were left unchanged other than that.

-Also fixed the link for: "[Learn C# on Windows, OSX or Linux with the .NET Core Koans]"in the README.md which currently routes to 404

Please let me know if the are any issues with this commit and anything I can improve upon :nerd_face:

2023-04-09 11:13 UTC, MaxAtoms requested changes
Just some minor suggestions/additions 🙂

2023-04-09 11:13 UTC, MaxAtoms commented on README.md
> If you are interested in learning VB.NET or the Full .NET Framework (windows only), please look at his fine work.

I suggest we change this sentence to:

> If you are interested in learning VB.NET, please look at his fine work.

The .NET Framework Koans do not address legacy .NET Framework functionality, as far as I can tell. Additionally, .NET has replaced the old .NET Framework.

2023-04-09 11:13 UTC, MaxAtoms commented on DotNetKoans.csproj
>      <VersionPrefix>3.1.0</VersionPrefix>
You missed the `Core` in the `<Description>` 😉

2023-04-09 15:41 UTC, KGonzalezASC commented on .vscode/launch.json
> +            "name": ".NET Launch (console)",
Would I also need to change "program" value to match the naming scheme?

2023-04-09 16:04 UTC, KGonzalezASC commented on DotNetKoans.csproj
> -    <AssemblyName>DotNetCoreKoans</AssemblyName>
I think it was deleted by accident, sorry about that

2023-04-09 16:15 UTC, KGonzalezASC commented on .all-contributorsrc
> +  "projectName": "DotNetKoans",
I think keeping it the same is best if the change is uncertain. I resolved and commit all the changes suggested let me know if there anything that need to be done on my end!

2023-04-12 21:17 UTC, MaxAtoms commented on .vscode/launch.json
> +            "name": ".NET Launch (console)",
Yes, that needs to be changed as well.
I have noted this in this separate comment below: https://github.com/NotMyself/DotNetCoreKoans/pull/184#discussion_r1161263897

2023-04-12 21:24 UTC, MaxAtoms commented on .vscode/launch.json
> +            "name": ".NET Launch (console)",
I changed the program path myself. Thanks for giving me write access to your branch that was very helpful 🙂

2023-04-12 21:25 UTC, MaxAtoms approved these changes

2023-04-12 21:28 UTC, merged

2023-04-12 21:36 UTC, MaxAtoms commented
https://github.com/all-contributors please add @KGonzalezASC for code

2023-04-12 21:38 UTC, MaxAtoms commented
@all-contributors please add @KGonzalezASC for code

2023-04-12 21:40 UTC, MaxAtoms commented on .all-contributorsrc
> +  "projectName": "DotNetKoans",
The bot actually reverts the change by itself: https://github.com/NotMyself/DotNetCoreKoans/blob/e0d70b7890ce444682738d5d052a43240ef5cb3a/.all-contributorsrc#L358